## Practice Questions - Functions

### Create functions for problems from weeks 1 & 2

#### Question 1: 

Create a function which takes 2 lists and a choice of **append(), extend(), insert(), and concatenation**, then returns the added list according to the selected choice. 

function call &rarr; add_lists (list_1, list_2, use_append) \
returns &rarr; [list_1, list_2]

In [13]:
# Solution - 1

def addLists (list1, list2, method):
    theReturnList = [list1]
    if method == "useAppend":
        theReturnList.append(list2)
    elif method == "useExtend":
        theReturnList.extend([list2])
    elif method == "useInsert":
        theReturnList.append([])
        for i in range(len(list2)):
            theReturnList[1].insert(i,list2[i])
    elif method == "useConcat":
        theReturnList += [list2]
    else:
        print("Invalid Method")
    return theReturnList

original = [22, 41, 33, 66, 8, 12, 90]
newList = [32, 45, 16, 11]

print ("Append =", addLists(original, newList, "useAppend"))
print ("Extend =", addLists(original, newList, "useExtend"))
print ("Insert =", addLists(original, newList, "useInsert"))
print ("Concat =", addLists(original, newList, "useConcat"))

Append = [[22, 41, 33, 66, 8, 12, 90], [32, 45, 16, 11]]
Extend = [[22, 41, 33, 66, 8, 12, 90], [32, 45, 16, 11]]
Insert = [[22, 41, 33, 66, 8, 12, 90], [32, 45, 16, 11]]
Concat = [[22, 41, 33, 66, 8, 12, 90], [32, 45, 16, 11]]


#### Question 2: 

Write a function that tests whether a list or a string is empty or not. 

function call &rarr; test_empty (list_1)\
returns &rarr; true or false

In [21]:
# Solution - 2

def testEmptyList(listIn):
    msg = "" 
    if len(listIn) == 0:
        msg = "The list was empty."
    while len(listIn) > 0:   
        lastIndex = len(listIn)-1
        print ("This list is not empty yet")
        print ("Popping " + str(listIn[lastIndex]))
        listIn.pop(lastIndex) 
        msg = "It took some work, but the list is now empty."
    return msg

def makeStringToList(stringIn):
    listOut = []
    for char in stringIn:
        listOut.append(char)
    print("String converted to list.")
    return listOut

def testEmptyString(myString):
    myList = makeStringToList(myString)
    return testEmptyList(myList)

list1 = []
print("Testing the empty list.")
print(testEmptyList(list1), "\n\n")

list1 = [1,2,3,4,5]
print("Testing the not empty list.")
print(testEmptyList(list1), "\n\n")

print("Testing the not empty string.")
print(testEmptyString("BUSA423.01W"))

Testing the empty list.
The list was empty. 


Testing the not empty list.
This list is not empty yet
Popping 5
This list is not empty yet
Popping 4
This list is not empty yet
Popping 3
This list is not empty yet
Popping 2
This list is not empty yet
Popping 1
It took some work, but the list is now empty. 


Testing the not empty string.
String converted to list.
This list is not empty yet
Popping W
This list is not empty yet
Popping 1
This list is not empty yet
Popping 0
This list is not empty yet
Popping .
This list is not empty yet
Popping 3
This list is not empty yet
Popping 2
This list is not empty yet
Popping 4
This list is not empty yet
Popping A
This list is not empty yet
Popping S
This list is not empty yet
Popping U
This list is not empty yet
Popping B
It took some work, but the list is now empty.


#### Question 3:

Write a function that takes an integer n and return a dictionary whose keys are integers 1, 2, 3, ... n and whose values ​​are 1! , 2! , 3! , … , n!

function call &rarr; factorial_dict (3)\
returns &rarr; { 1 : 1, 2 : 2, 3 : 6 }

In [23]:
# Solution - 3

import math

def factorialDict(n):
    factOut = {}
    for i in range(1,n+1):
        factOut.update({i : math.factorial(i)})
    return factOut

print ("Enter an integer: ")
n = int(input())

factorials = factorialDict(n)

for key,value in factorials.items():
    print(str(key) + " : " + str(value))

Enter an integer: 
1 : 1
2 : 2
3 : 6


#### Question 4: 
    
Write a function to identify the largest word in a string.

function call &rarr; largest_word ("Fear leads to anger, anger leads to hate, hate leads to suffering.")\
returns &rarr; "suffering"

In [31]:
# Solution - 4

def largestWord(stringIn):
    if "," in stringIn:
        stringIn = stringIn.replace(",", "")
    words = stringIn.split(" ")
    # print(words)          # to verify correct words in list
    theLargestWord = ""
    for word in words:
        if len(word) > len(theLargestWord):
            theLargestWord = word
    return theLargestWord

myString = "Fear leads to anger, anger leads to hate, hate leads to suffering"

print("The largest word in the string was: " + largestWord(myString))

The largest word in the string was: suffering


#### Question 5: 
    
Write a function to calculate the sum of the diagonal elements of a **n X n** matrix. 

function call &rarr; diagonal_sum(   [ [ 1  4  7 ]
 [ 2  5  8 ]
 [ 3  6  9 ] ] )\
returns &rarr; 15

In [32]:
# Solution - 5

import numpy as np

def diagonal_sum(matrixIn):
    return np.trace(matrixIn)

theMatrix = np.random.randint(20, size=(10,10))

print(theMatrix)
print("The sum of the main diagonal is:", diagonal_sum(theMatrix))


[[ 7  6  4 12 13 17  2 18  3 16]
 [12  6  4  7  6  2  6  0 13  3]
 [ 4 10  6 17 12 17 16 16  2 19]
 [ 6  0 10 18 12 19  0 16  0  8]
 [19 11 11  2 19 18 19 17 18  6]
 [ 4 15 17 12 15 16 10  4 16 11]
 [18  6 12 14  8  5 19 18 15  9]
 [11 12  1  0 17 11 19  5 14 15]
 [16  9 11 14 19 11  4 14 15  0]
 [ 7 14 19 19 17  3  1 19  5  9]]
The sum of the main diagonal is: 120


#### Question 6: Given a student score (between 0 and 100), write a function to evaluate the following criteria.

- Elgible for funding if the score is greater than 90
- Fail if the score is less than 70
- Need tutoring if they are not qualified for funding and havent failed.
 
function call → student_assessment(67)\
returns → Fail

In [35]:
# Solution - 6

def studentAssesment(scoreIn):
    if scoreIn > 90:
        return "Eligible for funding."
    elif scoreIn < 70:
        return "Failing"
    else:
        return "Needs toutoring."

students = {'stu1': 67, 'stu2': 77, 'stu3': 87, 'stu4': 97}
for key, value in students.items():
    print(key, " is ", studentAssesment(value))



stu1  is  Failing
stu2  is  Needs toutoring.
stu3  is  Needs toutoring.
stu4  is  Eligible for funding.


#### Question 7: Write a function to check if the given year is a leap year.

function call → cheap_leap(1995)\
returns → "No"

In [36]:
# Solution - 7

def cheapLeap(yearIn):
    if yearIn % 4 == 0:
        return "is a leap year"
    else:
        return "No"

for i in range (1990, 2001):
    print(i, cheapLeap(i))



1990 No
1991 No
1992 is a leap year
1993 No
1994 No
1995 No
1996 is a leap year
1997 No
1998 No
1999 No
2000 is a leap year


#### Question 8: Write a function which returns the number of days in the given month. (You can assume 28 days for February)

function call → get_days("January")\
returns → 31

In [41]:
# Solution - 8

longMonths = ('january', 'march', 'may', 'july', 'august', 'october', 'december')
shortMonths = ('april', 'june', 'september', 'november')

def getDays(monthIn):
    if monthIn in longMonths:
        return 31
    elif monthIn in shortMonths:
        return 30
    elif monthIn == 'february':
        return 28
    else:
        return "Invalid Entry"

print("Enter a month")
myMonth = input().lower()
print("The number of days in", myMonth.title(), "is", getDays(myMonth))


Enter a month
The number of days in May is 31


#### Question 9: Write a function which takes the user's weight(in lbs) and height(in inches), and then returns the bmi using the below formula.

BMI = Weight X 0.45359/((Height X 0.0254) X Height X 0.0254))

function call → calculate_bmi(150, 70)\
returns → 21.522

In [42]:
# Solution - 9

def calculateBMI(h,w):
    return (w * 0.45359)/((h * 0.0254)**2)

print("Enter weight:")
weight = float(input())
print("Enter height:")
height = float(input())

print(f'{calculateBMI(height, weight):.3f}')

Enter weight:
Enter height:
21.522


#### Question 10: Write a function to check whether a number is prime or not.

function call → check_prime(13)\
returns → "True"



**The code below was dirived from works found on** *[Wikipedia](https://en.wikipedia.org/wiki/Primality_test)*

Limited to *i in range (1, 8)* for time sake. 

In [7]:
# Solution - 10     with a little help from Wikipedia

def checkPrime(n):
    if n <= 3: 
        return n > 1
    elif not n%2 or not n%3:
        return False
    else:                
        i = 5            
        end = int(n**0.5)
        while i <= end:                                 
            if not n%i or not n%(i+2):                  
                return False
            i += 6                                      
        return True
    
# primes = []

for i in range (1,8):
    count = 0
    for n in range (1, 10 ** i):
        if checkPrime(n):
            count += 1
            #primes.append(n)        
    print("There are", count, "prime numbers from 1 to", n)
    

There are 4 prime numbers from 1 to 9
There are 25 prime numbers from 1 to 99
There are 168 prime numbers from 1 to 999
There are 1229 prime numbers from 1 to 9999
There are 9592 prime numbers from 1 to 99999
There are 78498 prime numbers from 1 to 999999
There are 664579 prime numbers from 1 to 9999999
