## Practice Questions - Strings & Data Structures

#### Question 1: 

Given an original list consiting of values: 22, 41, 33, 66, 8, 12 and 90. Use **append(), extend(), insert(), and concatenation** to add the values 32, 45, 16 and 11 to the list. 

In [1]:
# Solution - 1 

# the original list
original = [22, 41, 33, 66, 8, 12, 90]

# append() the second value skipping the first for instertion
original.append(45)

# extend() using the third value
original.extend([16])

# insert() the First value into it's spot at the beginning of the appended list
original.insert(7, 32)

# + the fourth and final value
original = original + [11]

print(original)

[22, 41, 33, 66, 8, 12, 90, 32, 45, 16, 11]


#### Question 2: 

Write a Python program that tests whether a list is empty or not. Repeat the task for testing an empty string.

In [2]:
# Solution - 2

myList = [1,2,3,4,5,6]                                  # create a not empty list

while len(myList) > 0:                                  # check if list is empty
    lastIndex = len(myList)-1
    print ("This list is not empty yet")
    print ("Popping " + str(myList[lastIndex]))
    myList.pop(lastIndex)                               # if the list is not empty pop the last item from the list
print ("Now it is!!")                                   # after all items have been popped from the list it is now empty. 

myString = "BUSA423.01W"                                # create a not empty string

while len(myString) > 0:                                # iterate through the string 
    lastIndex = len(myString)-1
    print ("This string is not empty yet")
    print ("Removing " + str(myString[lastIndex]))
    tempString = "" 
    for i in range(lastIndex):                          # create a tempString that holds the current string less the last char
        tempString = tempString + myString[i]
    myString = tempString                               # assign the tempString to myString
print ("Now it is!!")                                   # after all the characters are removed the string is now empty.

This list is not empty yet
Popping 6
This list is not empty yet
Popping 5
This list is not empty yet
Popping 4
This list is not empty yet
Popping 3
This list is not empty yet
Popping 2
This list is not empty yet
Popping 1
Now it is!!
This string is not empty yet
Removing W
This string is not empty yet
Removing 1
This string is not empty yet
Removing 0
This string is not empty yet
Removing .
This string is not empty yet
Removing 3
This string is not empty yet
Removing 2
This string is not empty yet
Removing 4
This string is not empty yet
Removing A
This string is not empty yet
Removing S
This string is not empty yet
Removing U
This string is not empty yet
Removing B
Now it is!!


#### Question 3: 

- How many times does "dream" appear in the text?

- Where is this text from? 

- Create a python code to print the text. 

*Added line numbers for visualization*

1. Dream on\
2. Dream on\
3. I dream on\
4. Dream a little, I'll dream on\
5. Dream on\
6. I dream on\
7. I dream on
8. 
9. Dream a little, I'll dream on\
10. Dream on\
11. Dream on\
12. Dream on\
13. I'll dream on\
14. Dream on\
15. Dream on\
16. I dream on

#### Question 3 answers:

- The word . *lower (dream)* appears 17 times in the text. 
- Song titled "Dream On" originally from Aerosmith's 1973 debut album

In [3]:
# Solution - 3
dream = [1,2,5,10,11,12,14,15]
iDream = [3,6,7,16]
dreamLittle = [4,9]
illDream = [4,9,13]

for i in range(1, 17):
    if i in dream:
        print("Dream on")
    elif i in iDream:
        print("I dream on")
    elif i in dreamLittle and i in illDream:
        print("Dream a little, I'll dream on")
    elif i in illDream:
        print("I'll dream on")
    else:
        print("")

Dream on
Dream on
I dream on
Dream a little, I'll dream on
Dream on
I dream on
I dream on

Dream a little, I'll dream on
Dream on
Dream on
Dream on
I'll dream on
Dream on
Dream on
I dream on


#### Question 4: 

Create a dictionary, with keys being the name of employees: Oliver, Myers, Noah and Fallon. 

Add the values age (random - between 40 and 60), income (random between 100,000 and 150,000) and rating (random between 3.0 and 5.0) 

In [4]:
# Solution - 4
import random

employees = {'Oliver' : {}, 'Myers' : {}, 'Noah' : {}, 'Fallon' : {}}

for employee in employees:
    employees[employee].update({'age' : random.randint(40,60)})
    employees[employee].update({'income' : random.randint(100000,150000)})
    employees[employee].update({'rating' : random.uniform(3.0,5.0)})

for employee in employees:
    print(employee + ": " + str(employees[employee]))
    

Oliver: {'age': 47, 'income': 117309, 'rating': 3.0071379123228534}
Myers: {'age': 56, 'income': 139701, 'rating': 4.167082091851874}
Noah: {'age': 41, 'income': 106816, 'rating': 4.6866810641316805}
Fallon: {'age': 58, 'income': 143678, 'rating': 4.763591101769724}


#### Question 5: 

Create the following student data into 2 sub dictionaries based on the scores. (score <= 10 & score > 10)

In [5]:
# Solution - 5

students = {"student_1" : 13 , "student_2" : 17 , "student_3" : 9 , "student_4" : 15 , "student_5" : 8 , "student_6" : 14 , 
            "student_7" : 16 , "student_8" : 12 , "student_9" : 13 , "student_10" : 15 , "student_11" : 14 , "student_112" : 9 , 
            "student_13" : 10 , "student_14" : 12 , "student_15" : 13 , "student_16" : 7 , "student_17" : 12 , "student_18" : 15 , 
            "student_19" : 9 , "student_20" : 17 ,}

upto10 = {}
over10 = {}

for student in students:
    if students[student] > 10:
        over10.update({student: students[student]})
    else:
        upto10.update({student: students[student]})

print("<= 10 " + str(upto10))
print("")
print("> 10 " + str(over10))

        

<= 10 {'student_3': 9, 'student_5': 8, 'student_112': 9, 'student_13': 10, 'student_16': 7, 'student_19': 9}

> 10 {'student_1': 13, 'student_2': 17, 'student_4': 15, 'student_6': 14, 'student_7': 16, 'student_8': 12, 'student_9': 13, 'student_10': 15, 'student_11': 14, 'student_14': 12, 'student_15': 13, 'student_17': 12, 'student_18': 15, 'student_20': 17}


#### Question 6: 


Write a python program that asks the user to enter an integer n and return a dictionary whose keys are integers 1, 2, 3, ... n and whose values ​​are 1! , 2! , 3! , … , n!

In [6]:
# Solution - 6

import math

print ("Enter an integer: ")
n = int(input())

factorials = {}

for i in range(1,n+1):
    factorials.update({i : math.factorial(i)})

for key,value in factorials.items():
    print(str(key) + " : " + str(value))
    

Enter an integer: 
1 : 1
2 : 2
3 : 6
4 : 24
5 : 120
6 : 720
7 : 5040
8 : 40320
9 : 362880
10 : 3628800


#### Question 7: 
    
Write a program to identify the largest word in a string.

In [7]:
# Solution - 7
myString = "The quick brown fox jumped over the lazy dog"

words = myString.split(" ")

theLargestWord = ""
for word in words:
    if len(word) > len(theLargestWord):
        theLargestWord = word

print("The largest word in the string was: " + theLargestWord)

The largest word in the string was: jumped


#### Question 8: 
    
Given an integer array, write a program to identify all the rows with values greater than the mean of the entire data.

In [8]:
# Solution - 8
import numpy as np

myArray = np.random.randint(1000, size=(10,10))
print(myArray)

arrMean = np.mean(myArray)
print("Mean = " + str(arrMean))

rows = []
for i in range(len(myArray)):
    for j in myArray[i]:
        #print(j)
        if j > arrMean:
            rows.append(i)
            break

print(rows)



[[145 976 744 853 789 635 655 568 223 814]
 [804 442 551 973 755 618 950 397 325 237]
 [644  50 946 835 357 342 187 255 317  61]
 [238 722 296 509 858 129 211 774 443 256]
 [501 798 273  11 646 460  13 600 530 600]
 [959 351 312 656 176 213 572 816 894 451]
 [ 49 564 634 916 673  89 342 342 661 300]
 [306 593 454 722 405 400 780 480 912  46]
 [864 936 774 720  63  85 749  49 589 691]
 [564 923 161 179 831 879 829  25 578 678]]
Mean = 515.51
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


#### Question 9: 
    
Given an array of strings, write a program to create a new array which contains the lengths of the strings in ascending order

In [9]:
# Solution - 9
import numpy as np

myString = "The quick brown fox jumped over the lazy dog"
words = myString.split(" ")
arrStrings = np.array(words)
sortedList = []

for word in arrStrings:
    if len(sortedList) < 1:                 # new list
        sortedList.append(word)
    elif len(sortedList) == 1:              # one word list
        if len(word) > len(sortedList[0]):
            sortedList.append(word)
        else:
            sortedList.insert(0, word)
    else:                                   # multiple word list
        for i in range(len(sortedList)):
            if i == len(sortedList) - 1:
                sortedList.append(word)
                break
            elif len(word) >= len(sortedList[i]) and len(word) < len(sortedList[i+1]):
                sortedList.insert(i+1, word)
                break

sortedArray = np.array(sortedList)
print(sortedArray)
print(type(sortedArray))




['The' 'fox' 'the' 'dog' 'over' 'lazy' 'quick' 'brown' 'jumped']
<class 'numpy.ndarray'>


#### Question 10: 
    
Write a program to calculate the sum of the diagonal elements of a **n X n** matrix. 

In [10]:
# Solution - 10
import numpy as np

theMatrix = np.random.randint(20, size=(10,10))

print(theMatrix)
print("The sum of the main diagonal is:")
print(np.trace(theMatrix))

[[ 8  4 18  6  5 18 13  1  0  3]
 [ 0  0 11 12 10 16  9  2 11 13]
 [ 6 12 10 19  5 15 14 11  1 18]
 [16  6  5 19  9 12 18  8  8 16]
 [16  8  4  6  9 11 11  8  1 17]
 [11 16  5  0 18  2 11  8  6  8]
 [18 12  5  7  6  8 19  4  9 13]
 [11  6  0 12 12  4  0 13  2  2]
 [15  3  0 16 11  3  9  1 10  3]
 [ 3 11 11  7  0  4  4  2  2 10]]
The sum of the main diagonal is:
100
